((nil . ((cider-clojure-cli-global-options . "-A:dev:test:cljs:spec-alpha:malli:test-check:instaparse")
         (cider-preferred-build-tool           . clojure-cli)
         (cider-redirect-server-output-to-repl . t)
         (cider-repl-display-help-banner       . nil)
         (clojure-toplevel-inside-comment-form . t)
         (cider-default-cljs-repl . node)))
 (clojure . ((eval . (define-clojure-indent
                       (assoc 0)
                       (for-all 1)
                       (ex-info 0))))))
